before_script: 
  - "sudo apt-get install libboost-test-dev -y"
  - "echo \"deb http://archive.ubuntu.com/ubuntu xenial main universe\" | sudo tee -a /etc/apt/sources.list"
  - "sudo apt-get update -qq"
deploy: 
  provider: script
  script: 
    - "curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u c-a1r:$BINTRAY_API_KEY \"https://api.bintray.com/content/c-a1r/otus/allocator/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1\""
  skip_cleanup: true
  true: 
    branch: main
language: cpp
script: 
  - "cmake ."
  - "cmake --build ."
  - "cmake --build . --target test"
  - "cmake --build . --target package"